In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [7]:
a = np.arange(1,12,2)

In [8]:
a

array([ 1,  3,  5,  7,  9, 11])

In [10]:
a = np.linspace(1,12,6)

In [11]:
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [12]:
a.reshape(3,2)

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [14]:
a.size

6

In [15]:
a.dtype

dtype('float64')

a.itemsize

#### print the element memory size

In [17]:
a.itemsize

8