In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [7]:
a = np.arange(1,12,2)

In [8]:
a

array([ 1,  3,  5,  7,  9, 11])

In [10]:
a = np.linspace(1,12,6)

In [11]:
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [12]:
a.reshape(3,2)

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [14]:
a.size

6

In [15]:
a.dtype

dtype('float64')

a.itemsize

#### print the element memory size

In [17]:
a.itemsize

8

create multi dimetional array

In [19]:
b = np.array([(1.5,2,3),(4,5,6)])

In [20]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [21]:
a < 4

array([ True,  True, False, False, False, False])

In [22]:
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [23]:
a * 3

array([ 3. ,  9.6, 16.2, 22.8, 29.4, 36. ])

In [24]:
a = np.zeros((3,4))

In [25]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
In [24]

'a = np.zeros((3,4))'

In [28]:
a = np.ones((2,3))

In [29]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
a = np.array([2,3,4],dtype=np.int16)

In [31]:
a

array([2, 3, 4], dtype=int16)

In [32]:
a.dtype

dtype('int16')

In [33]:
a = np.random.random((2,3))

In [34]:
a

array([[0.61390297, 0.55366564, 0.81029604],
       [0.66645811, 0.01018842, 0.28096512]])

In [35]:
np.set_printoptions(precision=2,suppress=True)

In [36]:
a

array([[0.61, 0.55, 0.81],
       [0.67, 0.01, 0.28]])

In [37]:
a = np.random.randint(0,10,5)

In [38]:
a

array([7, 5, 8, 0, 1])

In [39]:
a.sum()

21

In [40]:
a.min()

0

In [41]:
a.max()

8

In [42]:
a.std()

3.1874754901018454

In [43]:
a = np.random.randint(1,10,6)

In [44]:
a = a.reshape((3,2))

In [45]:
a

array([[3, 2],
       [5, 3],
       [9, 6]])

In [46]:
a.sum(axis=1)

array([ 5,  8, 15])

np.loadxt

In [49]:
a = np.arange(10)

In [50]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.random.shuffle(a)

In [52]:
a

array([6, 4, 8, 3, 2, 0, 7, 5, 1, 9])

In [53]:
np.random.choice(a)

0

In [55]:
np.random.randint(5,10,2)

array([5, 6])

In [57]:
test_array = np.arange(1000)

In [58]:
test_list = list(range(1000))

In [59]:
%timeit sum(test_list)

7.24 µs ± 61.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [60]:
%timeit np.sum(test_array)

3.26 µs ± 60.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
